### ISSUE TITLE
Has this code been used to successfully train a model that gives good predictions?

### ISSUE THREAD

**Issue by alexryan** [sydsim/personlab-tf#12]
I've tried this version and 2 forks of this code base 
[strawberryfg](https://github.com/strawberryfg/personlab-tf)
[junedgar](https://github.com/junedgar/personlab-tf)
and they all give me the same error when I try to train it.

[Issue #7](https://github.com/sydsim/personlab-tf/issues/7) 
which has not been responded to.

Has anyone been able to use this code to train a model?
If so, how accurate are the predictions?

sydsim, you said in [this reddit discussion](https://www.reddit.com/r/MachineLearning/comments/9cjyo0/p_tensorflow_implementation_of_personlab_person/) that you had a trained model but that it was too big to upload to github.

If you, or anyone else, is willing to share, I have created a google cloud storage bucket to upload you model:
`gs://personlab-tf-model/`

**Comment by sydsim** [comment]
https://drive.google.com/file/d/1v_zVLxQSXI69jFIzOZoL0pRWQ1wwoz0f/view?usp=sharing
trained model with mobilenet v2
