### ISSUE TITLE
Further rescale seems unnecessary

### ISSUE THREAD

**Issue by noeruh** [sydsim/personlab-tf#5]
https://github.com/sydsim/personlab-tf/blob/a2814756868634d087ce9b8226c9e241338aa68a/personlab/models/model_base.py#L47

`tf.image.resize_images` already resizes the offsets according to target height/width, why do we do a further rescaling here? I have tried to remove the rescaling step and it seem to work just fine.

**Comment by sydsim** [comment]
`tf.image.resize_images` resizes the contents but doesn't rescale the values on it.
`so_x, mo_x, lo_x` are indicating the offset vectors. if the image size gets doubled, the offset vectors should be also doubled to point the same position.
